# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 463b1fb
_src_path: /home/bukzor/repo/github.com/bukzor/template.python-project
author_email: buck.2019+python-template@gmail.com
author_name: Buck Evan
description: Python project template with copier support
github_username: bukzor
project_name: bukzor-template-python-project
python_version: '3.13'
